services:
  mkdocs:
    build: .
    container_name: mkdocs-docs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
      - /docs/site  # Exclude site directory from volume mount
    environment:
      - PYTHONUNBUFFERED=1
    command: mkdocs serve --dev-addr=0.0.0.0:8000
    restart: unless-stopped

  mkdocs-build:
    build: .
    container_name: mkdocs-build
    volumes:
      - .:/docs
    command: mkdocs build --clean
    profiles:
      - build

  mkdocs-gh-deploy:
    build: .
    container_name: mkdocs-gh-deploy
    volumes:
      - .:/docs
      - ~/.ssh:/root/.ssh:ro  # Mount SSH keys for GitHub authentication
    environment:
      - GIT_COMMITTER_NAME=GitHub Actions
      - GIT_COMMITTER_EMAIL=actions@github.com
      - GIT_AUTHOR_NAME=GitHub Actions
      - GIT_AUTHOR_EMAIL=actions@github.com
    command: mkdocs gh-deploy --force
    dns:
      - 8.8.8.8
      - 8.8.4.4
    profiles:
      - deploy

networks:
  default:
    name: mkdocs-network